#!/bin/bash

set -e
yarn install

HAS_ERROR=false
for p in $(find . -name protocol.json); do
  if ! "$(yarn bin)/ajv" -s docs/protocol-schema.json -d "$p"; then
    HAS_ERROR=true
  fi
done

if $HAS_ERROR; then
  echo "Validation failed"
  exit 1
else
  echo "Success"
  exit 0
fi

